### ISSUE TITLE
2 Q about blueprints url_prefix & manage.py imports

### ISSUE THREAD

**Issue by ahmedloay** [cosmic-byte/flask-restplus-boilerplate#1]
Hi,

first:
I want to add a prefix to each blueprint I create like `/api/v1/` but when I edit the line
`blueprint = Blueprint('api', __name__)`  in `app/__init__.py'`  to `blueprint = Blueprint('api', __name__, url_prefix='/api/v1/')` then run the tests, they fail! Even if I prefixed the URLs in the test functions by `/api/v1/`.

would you please recommend the right way to do so?

second:
May I ask why did you add these imports `from app.main.model import user, blacklist` into manage.py? I don't see any use for them there. If there is, would you please illustrate?

Thanks in advance.

**Comment by cosmic-byte** [comment]
Hello @ahmedloay  sorry for late response!!

To address your first issue, I will need to see the `url_prefix` in your test cases cos 
`blueprint = Blueprint('api', __name__, url_prefix='/api/v1/')` works fine for me.

Secondly those imports are there for `Flask_Migrate`. Any model that is not imported on the same file as the instance of `flask_migrate` will not be detected by 'flask_migrate` when changes are made on the model.
