### ISSUE TITLE
Missing code snippets in the guide

### ISSUE THREAD

**Issue by ialmoqren** [cosmic-byte/flask-restplus-boilerplate#10]
While reading the [guide](https://github.com/cosmic-byte/flask-restplus-boilerplate), I see that the code snippets are missing for some reason, such as this:
![image](https://user-images.githubusercontent.com/26797924/58561742-7dac5d80-8230-11e9-9446-d8f6c6ddd30c.png)

Is there a way to get them, I would love to follow up with the guide.

Thanks a lot for your effort.

**Comment by zrehman-ssi** [comment]
Hi @ialmoqren,

You can go to the code in repository, and you will be able to see manage.py. The mentioned lines are from that file. Just for making it easy for you, here are those lines.

```
import os
import unittest

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager 
from app import blueprint
from app.main import create_app, db
from app.main.model import user, blacklist
app = create_app(os.getenv('BOILERPLATE_ENV') or 'dev')
```
