### ISSUE TITLE
[Q] How to create admin user

### ISSUE THREAD

**Issue by jerosa** [cosmic-byte/flask-restplus-boilerplate#11]
Hi,

First of all I need to thank you for this project and the helpful guide.
I was able to follow it to the end but I am unable to create an admin user, maybe I am missing something.

The only idea I had was to edit the controller to allow entering whether it's admin or not and once created reverit it, but I don't think it's a good solution.

Thanks in advance

**Comment by bigwolfdogroar** [comment]
You can create a user first and change admin 0->1. 
Now, you get a admin user.

**Comment by zrehman-ssi** [comment]
Hi @jerosa,

I guess the best solution is to create a service that is going to initialize the db. The script should be idempotent. Created a new command in manage.py file for initializing the database with default values that would be required for the appliation e.g. some default admin. Within that command you can call your service initialization script and create the new users if doesn't exist. 

Regards

**Comment by jerosa** [comment]
That seems a good aproach. Thank you
