### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sgsmittal226** [cosmic-byte/flask-restplus-boilerplate#17]
I  just installed all required packages mentioned in this example.  but it is not working on running manage.py

Command : - python manage.py run

![image](https://user-images.githubusercontent.com/40248398/69121377-3a85c580-0ac2-11ea-96c9-031b031facc8.png)

![image](https://user-images.githubusercontent.com/40248398/69121288-f4c8fd00-0ac1-11ea-8d9e-97a986870b0d.png)

**Comment by zrehman-ssi** [comment]
Hi @sgupta226,

Try adding / at the end or url 

What you are trying 
_http://127.0.0.1/user_

What should work
**http://127.0.0.1/user/**
