### ISSUE TITLE
Replace Flask-RESTPlus by Flask-RestX

### ISSUE THREAD

**Issue by Frankkkkk** [cosmic-byte/flask-restplus-boilerplate#22]
As stated by [Flask-RESTPlus authors](https://github.com/noirbizarre/flask-restplus/issues/770), the project is considered abandoned and should be superseded by Flask-RestX

Cheers

**Comment by cosmic-byte** [comment]
> As stated by [Flask-RESTPlus authors](https://github.com/noirbizarre/flask-restplus/issues/770), the project is considered abandoned and should be superseded by Flask-RestX
> 
> Cheers

Thanks for bringing this up. I will make the changes asap but if you can, make a pr.

**Comment by cosmic-byte** [comment]
Hello @Frankkkkk, I've migrated to Flask-RestX. Thanks
