### ISSUE TITLE
Tests failing from incompatible version of SQLAlchemy Fix

### ISSUE THREAD

**Issue by fvolcic** [cosmic-byte/flask-restplus-boilerplate#32]
When setting up the boilerplate application, I was having a lot of trouble with the tests failing. After some reading, I stumbled across this article (https://exerror.com/attributeerror-cant-set-attribute-when-connecting-to-sqlite-database-with-flask/). To fix the issue, I had to alter the requirements.txt file and change "SQLAlchemy>=1.3.0" to "SQLAlchemy==1.3.0". This changed fixed the failing tests.
[requirements.txt](https://github.com/cosmic-byte/flask-restplus-boilerplate/files/6481817/requirements.txt)

**Comment by cosmic-byte** [comment]
Fixed by #29
