### ISSUE TITLE
Question: token_require, access user object

### ISSUE THREAD

**Issue by spoetnik** [cosmic-byte/flask-restplus-boilerplate#4]
Say, I have an endpoint with the '`token_required`' decorator. How can I access the current logged in user account in a service class?

To give an example, I have an endpoint 'my-blogposts' that shows only blogpost from the current author, so I want to filter something like: `return Posts.query.filter_by(author=g.user.get('id')).all()` or something.

**Comment by cosmic-byte** [comment]
Hi, @spoetnik sorry for the late response. You can access the logged in user using the `get_logged_in_user` method in the `Auth` class 

```python
from flask import request

user, status = Auth.get_logged_in_user(request)
```
