### ISSUE TITLE
[Q] How to get uwsgi work with the project structure

### ISSUE THREAD

**Issue by samip5** [cosmic-byte/flask-restplus-boilerplate#7]
How should I get uwsgi working with this project structure?

I were unable to comment on the article so I'm asking here.

test.ini:
```ini
; test.ini

[uwsgi]
protocol = uwsgi

; This is the name of our Python file
; minus the file extension
module = app

; This is the name of the variable
; in our script that will be called
callable = main

master = true

; Set uWSGI to start up 5 workers
processes = 5

; We use the port 5000 which we will
; then expose on our Dockerfile
http = 0.0.0.0:8080
vacuum = true

die-on-term = true
```

Error:
```py
uwsgi -s /tmp/yourapplication.sock --ini configs/test.ini --plugin python3
[uWSGI] getting INI configuration from configs/test.ini
open("./python3_plugin.so"): No such file or directory [core/utils.c line 3724]
!!! UNABLE to load uWSGI plugin: ./python3_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.18 (64bit) on [Sun Feb 10 12:33:36 2019] ***
compiled with version: 7.3.0 on 10 February 2019 08:38:52
os: Linux-4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
nodename: Ryzen-Gaming-Linux
machine: x86_64
clock source: unix
detected number of CPU cores: 12
current working directory: /home/sm/PycharmProjects/REST-API
detected binary path: /home/sm/PycharmProjects/REST-API/venv/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
your processes number limit is 63338
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 0.0.0.0:8080 fd 3
uwsgi socket 0 bound to UNIX address /tmp/yourapplication.sock fd 6
Python version: 3.7.1 (default, Oct 22 2018, 11:21:55)  [GCC 8.2.0]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55da5c6e5430
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 437424 bytes (427 KB) for 5 cores
*** Operational MODE: preforking ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55da5c6e5430 pid: 9723 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 9723)
spawned uWSGI worker 1 (pid: 9724, cores: 1)
spawned uWSGI worker 2 (pid: 9725, cores: 1)
spawned uWSGI worker 3 (pid: 9726, cores: 1)
spawned uWSGI worker 4 (pid: 9727, cores: 1)
spawned uWSGI worker 5 (pid: 9728, cores: 1)
spawned uWSGI http 1 (pid: 9729)
TypeError: 'module' object is not callable
[pid: 9727|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 802 bytes} [Sun Feb 10 12:33:46 2019] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
TypeError: 'module' object is not callable
[pid: 9727|app: 0|req: 2/2] 127.0.0.1 () {40 vars in 833 bytes} [Sun Feb 10 12:33:46 2019] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
TypeError: 'module' object is not callable
[pid: 9728|app: 0|req: 1/3] 127.0.0.1 () {40 vars in 833 bytes} [Sun Feb 10 12:33:52 2019] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
^CSIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 9729)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
worker 5 buried after 1 seconds
goodbye to uWSGI.
VACUUM: unix socket /tmp/yourapplication.sock removed.
```

**Comment by amarnaud2** [comment]
> How should I get uwsgi working with this project structure?
> 
> I were unable to comment on the article so I'm asking here.
> 
> test.ini:
> 
> ```ini
> ; test.ini
> 
> [uwsgi]
> protocol = uwsgi
> 
> ; This is the name of our Python file
> ; minus the file extension
> module = app
> 
> ; This is the name of the variable
> ; in our script that will be called
> callable = main
> 
> master = true
> 
> ; Set uWSGI to start up 5 workers
> processes = 5
> 
> ; We use the port 5000 which we will
> ; then expose on our Dockerfile
> http = 0.0.0.0:8080
> vacuum = true
> 
> die-on-term = true
> ```
> 
> Error:
> 
> ```python
> uwsgi -s /tmp/yourapplication.sock --ini configs/test.ini --plugin python3
> [uWSGI] getting INI configuration from configs/test.ini
> open("./python3_plugin.so"): No such file or directory [core/utils.c line 3724]
> !!! UNABLE to load uWSGI plugin: ./python3_plugin.so: cannot open shared object file: No such file or directory !!!
> *** Starting uWSGI 2.0.18 (64bit) on [Sun Feb 10 12:33:36 2019] ***
> compiled with version: 7.3.0 on 10 February 2019 08:38:52
> os: Linux-4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
> nodename: Ryzen-Gaming-Linux
> machine: x86_64
> clock source: unix
> detected number of CPU cores: 12
> current working directory: /home/sm/PycharmProjects/REST-API
> detected binary path: /home/sm/PycharmProjects/REST-API/venv/bin/uwsgi
> !!! no internal routing support, rebuild with pcre support !!!
> your processes number limit is 63338
> your memory page size is 4096 bytes
> detected max file descriptor number: 1024
> lock engine: pthread robust mutexes
> thunder lock: disabled (you can enable it with --thunder-lock)
> uWSGI http bound on 0.0.0.0:8080 fd 3
> uwsgi socket 0 bound to UNIX address /tmp/yourapplication.sock fd 6
> Python version: 3.7.1 (default, Oct 22 2018, 11:21:55)  [GCC 8.2.0]
> *** Python threads support is disabled. You can enable it with --enable-threads ***
> Python main interpreter initialized at 0x55da5c6e5430
> your server socket listen backlog is limited to 100 connections
> your mercy for graceful operations on workers is 60 seconds
> mapped 437424 bytes (427 KB) for 5 cores
> *** Operational MODE: preforking ***
> WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55da5c6e5430 pid: 9723 (default app)
> *** uWSGI is running in multiple interpreter mode ***
> spawned uWSGI master process (pid: 9723)
> spawned uWSGI worker 1 (pid: 9724, cores: 1)
> spawned uWSGI worker 2 (pid: 9725, cores: 1)
> spawned uWSGI worker 3 (pid: 9726, cores: 1)
> spawned uWSGI worker 4 (pid: 9727, cores: 1)
> spawned uWSGI worker 5 (pid: 9728, cores: 1)
> spawned uWSGI http 1 (pid: 9729)
> TypeError: 'module' object is not callable
> [pid: 9727|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 802 bytes} [Sun Feb 10 12:33:46 2019] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
> TypeError: 'module' object is not callable
> [pid: 9727|app: 0|req: 2/2] 127.0.0.1 () {40 vars in 833 bytes} [Sun Feb 10 12:33:46 2019] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
> TypeError: 'module' object is not callable
> [pid: 9728|app: 0|req: 1/3] 127.0.0.1 () {40 vars in 833 bytes} [Sun Feb 10 12:33:52 2019] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
> ^CSIGINT/SIGQUIT received...killing workers...
> gateway "uWSGI http 1" has been buried (pid: 9729)
> worker 1 buried after 1 seconds
> worker 2 buried after 1 seconds
> worker 3 buried after 1 seconds
> worker 4 buried after 1 seconds
> worker 5 buried after 1 seconds
> goodbye to uWSGI.
> VACUUM: unix socket /tmp/yourapplication.sock removed.
> ```

Hello,

I'm also interested in using uWSGI but I can't figure it out. You posted on February so did you solve your problem ? Can you share how please ? 

Regards, Arnaud.

**Comment by amarnaud2** [comment]
> > How should I get uwsgi working with this project structure?
> > I were unable to comment on the article so I'm asking here.
> > test.ini:
> > ```ini
> > ; test.ini
> > 
> > [uwsgi]
> > protocol = uwsgi
> > 
> > ; This is the name of our Python file
> > ; minus the file extension
> > module = app
> > 
> > ; This is the name of the variable
> > ; in our script that will be called
> > callable = main
> > 
> > master = true
> > 
> > ; Set uWSGI to start up 5 workers
> > processes = 5
> > 
> > ; We use the port 5000 which we will
> > ; then expose on our Dockerfile
> > http = 0.0.0.0:8080
> > vacuum = true
> > 
> > die-on-term = true
> > ```
> > 
> > 
> > Error:
> > ```python
> > uwsgi -s /tmp/yourapplication.sock --ini configs/test.ini --plugin python3
> > [uWSGI] getting INI configuration from configs/test.ini
> > open("./python3_plugin.so"): No such file or directory [core/utils.c line 3724]
> > !!! UNABLE to load uWSGI plugin: ./python3_plugin.so: cannot open shared object file: No such file or directory !!!
> > *** Starting uWSGI 2.0.18 (64bit) on [Sun Feb 10 12:33:36 2019] ***
> > compiled with version: 7.3.0 on 10 February 2019 08:38:52
> > os: Linux-4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019
> > nodename: Ryzen-Gaming-Linux
> > machine: x86_64
> > clock source: unix
> > detected number of CPU cores: 12
> > current working directory: /home/sm/PycharmProjects/REST-API
> > detected binary path: /home/sm/PycharmProjects/REST-API/venv/bin/uwsgi
> > !!! no internal routing support, rebuild with pcre support !!!
> > your processes number limit is 63338
> > your memory page size is 4096 bytes
> > detected max file descriptor number: 1024
> > lock engine: pthread robust mutexes
> > thunder lock: disabled (you can enable it with --thunder-lock)
> > uWSGI http bound on 0.0.0.0:8080 fd 3
> > uwsgi socket 0 bound to UNIX address /tmp/yourapplication.sock fd 6
> > Python version: 3.7.1 (default, Oct 22 2018, 11:21:55)  [GCC 8.2.0]
> > *** Python threads support is disabled. You can enable it with --enable-threads ***
> > Python main interpreter initialized at 0x55da5c6e5430
> > your server socket listen backlog is limited to 100 connections
> > your mercy for graceful operations on workers is 60 seconds
> > mapped 437424 bytes (427 KB) for 5 cores
> > *** Operational MODE: preforking ***
> > WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55da5c6e5430 pid: 9723 (default app)
> > *** uWSGI is running in multiple interpreter mode ***
> > spawned uWSGI master process (pid: 9723)
> > spawned uWSGI worker 1 (pid: 9724, cores: 1)
> > spawned uWSGI worker 2 (pid: 9725, cores: 1)
> > spawned uWSGI worker 3 (pid: 9726, cores: 1)
> > spawned uWSGI worker 4 (pid: 9727, cores: 1)
> > spawned uWSGI worker 5 (pid: 9728, cores: 1)
> > spawned uWSGI http 1 (pid: 9729)
> > TypeError: 'module' object is not callable
> > [pid: 9727|app: 0|req: 1/1] 127.0.0.1 () {38 vars in 802 bytes} [Sun Feb 10 12:33:46 2019] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (0 switches on core 0)
> > TypeError: 'module' object is not callable
> > [pid: 9727|app: 0|req: 2/2] 127.0.0.1 () {40 vars in 833 bytes} [Sun Feb 10 12:33:46 2019] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
> > TypeError: 'module' object is not callable
> > [pid: 9728|app: 0|req: 1/3] 127.0.0.1 () {40 vars in 833 bytes} [Sun Feb 10 12:33:52 2019] GET / => generated 0 bytes in 0 msecs (HTTP/1.1 500) 0 headers in 0 bytes (1 switches on core 0)
> > ^CSIGINT/SIGQUIT received...killing workers...
> > gateway "uWSGI http 1" has been buried (pid: 9729)
> > worker 1 buried after 1 seconds
> > worker 2 buried after 1 seconds
> > worker 3 buried after 1 seconds
> > worker 4 buried after 1 seconds
> > worker 5 buried after 1 seconds
> > goodbye to uWSGI.
> > VACUUM: unix socket /tmp/yourapplication.sock removed.
> > ```
> 
> Hello,
> 
> I'm also interested in using uWSGI but I can't figure it out. You posted on February so did you solve your problem ? Can you share how please ?
> 
> Regards, Arnaud.

So, twenty minutes after writing my first message here, I found the beginning of a solution. 

If you rename the 'manage.py' in 'wsgi.py', then you can launch the app with: 
`uwsgi --socket 0.0.0.0:5000 --protocol=http -w wsgi:app`

As I'm a beginner in Python & Flask, please give your feedback if you read my message :-). 

My goal is to launch this application at the ubuntu system start so any help is more than welcome in creating the service script and configuration. 

Regards, Arnaud

**Comment by amarnaud2** [comment]
Hi guys ! 

I feel always better after a good lunch :-). 

So I have good news, it's almost working by doing this: 
- I keep the part I renamed the 'manage.py' in 'wsgi.py'
- I created a file called 'genericflaskapi.py' at the root level (same level as 'wsgi.py') with the following code: 

`
[uwsgi]
; Python version to use
; plugins-dir = <path_to_your_plugin_directory>
plugin = python3

protocol = uwsgi

; This is the name of our Python file
; minus the file extension
module = wsgi

; This is the name of the variable
; in our script that will be called
callable = app

master = true

; Set uWSGI to start up 5 workers
processes = 5

; Enable threads
enable-threads = true

; We use the port 5000 (which we will
; then expose on our Dockerfile)
http = 0.0.0.0:5000
vacuum = true

die-on-term = true
`

Then, you can launch the app with the following command: 
`uwsgi -s /tmp/genericflaskapi.sock --ini genericflaskapi.ini`

Open your browser at http://127.0.0.1:5000 and it works. 

I think a good tuto about creating Ubuntu service should be enough to complete the job. 

Regards, Arnaud

**Comment by ss13ms110** [comment]
I am also running into same issue. However, after trying Arnaud's solution I got this error.
`uwsgi: invalid option -- 'w'`

Can you help?
Thank you

Best
Shubham
